// Extracts the data the port needs from an OpenSpookyHouse GameMaker checkout:
// room layouts, the bitmap font metrics/atlas, the depth-mask PNGs and the
// debug sprite metadata. Everything extracted here is part of the GPLv3
// OpenSpookyHouse project itself; no Hugo's House of Horrors data is involved.
//
// Usage: node tools/extract-osh.mjs /path/to/openspookyhouse
import fs from 'node:fs';
import path from 'node:path';

const src = process.argv[2];
if (!src || !fs.existsSync(path.join(src, 'OpenSpookyHouse.yyp'))) {
  console.error('usage: node tools/extract-osh.mjs <openspookyhouse checkout>');
  process.exit(1);
}
const here = path.dirname(new URL(import.meta.url).pathname);
const webRoot = path.resolve(here, '..');

// GameMaker .yy files are JSON with trailing commas.
const loadYY = (p) => JSON.parse(fs.readFileSync(p, 'utf8').replace(/,(\s*[}\]])/g, '$1'));

// ---- Rooms ---------------------------------------------------------------
const rooms = {};
for (const dir of fs.readdirSync(path.join(src, 'rooms')).sort()) {
  const j = loadYY(path.join(src, 'rooms', dir, dir + '.yy'));
  const byName = new Map();
  for (const layer of j.layers) {
    for (const inst of layer.instances || []) {
      byName.set(inst.name, {
        obj: inst.objectId.name,
        x: inst.x, y: inst.y,
        sx: inst.scaleX, sy: inst.scaleY,
        depth: layer.depth,
      });
    }
  }
  const order = (j.instanceCreationOrder || []).map((r) => r.name).filter((n) => byName.has(n));
  for (const n of byName.keys()) if (!order.includes(n)) order.push(n);
  rooms[j.name] = {
    width: j.roomSettings.Width,
    height: j.roomSettings.Height,
    instances: order.map((n) => byName.get(n)),
  };
}

// ---- Sprites shipped with OSH (debug squares + depth masks) ---------------
const sprites = {};
const masksOut = path.join(webRoot, 'static', 'masks');
fs.mkdirSync(masksOut, { recursive: true });
for (const dir of fs.readdirSync(path.join(src, 'sprites')).sort()) {
  const j = loadYY(path.join(src, 'sprites', dir, dir + '.yy'));
  const frame = j.frames[0].name;
  sprites[j.name] = {
    width: j.width, height: j.height,
    xorigin: j.sequence.xorigin, yorigin: j.sequence.yorigin,
    bbox: [j.bbox_left, j.bbox_right, j.bbox_top, j.bbox_bottom],
  };
  if (dir.startsWith('spr_mask_')) {
    fs.copyFileSync(path.join(src, 'sprites', dir, frame + '.png'), path.join(masksOut, dir + '.png'));
  }
}

// ---- Font ------------------------------------------------------------------
const font = loadYY(path.join(src, 'fonts', 'fnt_cmd', 'fnt_cmd.yy'));
const glyphs = {};
for (const g of Object.values(font.glyphs)) {
  glyphs[g.character] = [g.x, g.y, g.w, g.h, g.shift, g.offset];
}
fs.copyFileSync(path.join(src, 'fonts', 'fnt_cmd', 'fnt_cmd.png'), path.join(webRoot, 'static', 'font.png'));

const out = `// Generated by tools/extract-osh.mjs from the OpenSpookyHouse GameMaker project.
// Do not edit by hand.
/* eslint-disable */
export const ROOMS: Record<string, { width: number; height: number; instances: { obj: string; x: number; y: number; sx: number; sy: number; depth: number }[] }> = ${JSON.stringify(rooms)};
export const BUILTIN_SPRITES: Record<string, { width: number; height: number; xorigin: number; yorigin: number; bbox: [number, number, number, number] }> = ${JSON.stringify(sprites)};
export const FONT = ${JSON.stringify({ size: font.size, lineHeight: font.lineHeight, glyphs })} as { size: number; lineHeight: number; glyphs: Record<string, [number, number, number, number, number, number]> };
`;
fs.writeFileSync(path.join(webRoot, 'src', 'game', 'data.generated.ts'), out);
console.log('rooms:', Object.keys(rooms).length, 'sprites:', Object.keys(sprites).length, 'glyphs:', Object.keys(glyphs).length);
